### ISSUE TITLE
Compiling VC1 fails

### ISSUE THREAD

**Issue by opticon** [jdleo/SMS-BOMBER#1]
When compiling VC1 in Kali Linux, using javac, errors return and the new file is not created. I have no use for the bomber.java file as the code doesn't appear to do any of the work that VC1 can. If you could review the files, and compile them, I'd be extremely grateful. I am running JRE 8 on Kali 2.0 2016.

Thanks in advance!

**Comment by jdleo** [comment]
No problem bro! I'll fix that right now! Yeah, I was gonna go another route and that's why I left bomber.java in there, probably should get rid of that

**Comment by jdleo** [comment]
@opticon okay sorry about this, I'm actually fixing it as we speak! :+1: :smile:

**Comment by jdleo** [comment]
@opticon https://github.com/jdleo/SMS-BOMBER/releases/tag/v0.3-jar that's the link for the new jar file (to run this you'll need JRE), or you can just compile the Bomber.java file yourself now! :smiley: It's all in one java file now
